apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 4
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: alexcui1/cs179i_alex_andrew:latest
        ports:
        - containerPort: 5000